services:
  back:
    image: assets_rebalance_backend:latest
    build: 
      context: .
      dockerfile: ./assets_rebalance_backend/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ApplicationKey=:q1qv;@OXdFv}=P
      - ASPNETCORE_ENVIRONMENT=Development
  front:
    image: assets_rebalance_frontend:latest
    build: 
      context: .
      dockerfile: ./assets_rebalance_frontend/Dockerfile
    environment:
      - NODE_ENV=development
    ports: 
      - "3000:3000"