apiVersion: apps/v1
kind: Deployment
metadata:
  name: assetsrebalanceback
  namespace: assetsrebalance
  labels:
    app: assetsrebalanceback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assetsrebalanceback
  template:
    metadata:
      labels:
        app: assetsrebalanceback
    spec:
      containers:
        - name: assetsrebalanceback
          image: patrickromao/assetsrebalancebackend:1.0.0-rcs-2
          env:
            - name: MongoDbSettings__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: assetsrebalanceback
                  key: mongodb_connstr
            - name: ApplicationKey
              valueFrom:
                secretKeyRef:
                  name: assetsrebalanceback
                  key: api_key
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"