apiVersion: v1
kind: Service
metadata:
  name: assetsrebalanceback
  namespace: assetsrebalance
spec:
  selector:
    app: assetsrebalanceback
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30080
  type: NodePort
